move_group:
  descartes_params:
    positional_tolerance: 0.0
    positional_tolerance_inc: 0.0
    roll_orientation_tolerance: 0.0
    pitch_orientation_tolerance: 0.0
    yaw_orientation_tolerance: 0.0
    orientation_tolerance_inc: 0.1

    debug:
      visual: true
      verbose: false